name: Project Feedback

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project feedback
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
      - name: install requirements
        working-directory: project
        run: pip install -r requirements.txt


  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project feedback
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      # Run grading feedback
      - name: Project feedback
        id: Pro_feedback
        shell: bash
        working-directory: project
        run: ./tests.sh


      # Create badges
      - name: Create badges Project 6
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: score_project6
          LABEL: "project6"
          STATUS: ${{ steps.ex_feedback.outputs.score_project5 }}
          COLOR: 1eb57f
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
