name: Project Feedback

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project feedback
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
      - name: install requirements
        working-directory: project
        run: pip install -r requirements.txt

      # Run grading feedback
      - name: Project feedback
        id: Pro_feedback
        shell: bash
        working-directory: project
        run: bash tests.sh

